/**
 * facs.js — The muscle registry.
 *
 * Every muscle of facial expression is a first-class, independently addressable
 * actuator. The LLM never sets an "emotion"; it innervates muscles one at a
 * time, exactly as motor cortex does. Emotion is what the observer infers from
 * the resulting pattern.
 *
 * Each entry carries:
 *   id          tool name exposed to the model
 *   au          FACS Action Unit code (Ekman & Friesen)
 *   muscle      anatomical name
 *   region      grouping for the UI
 *   bilateral   whether left/right can be innervated independently
 *   tau         onset time constant in ms — fast twitch vs slow
 *   ceiling     physiological maximum contraction (not every muscle reaches 1.0)
 *   antagonists muscles mechanically opposed to this one
 *   synergists  muscles partially recruited by this one (involuntary co-activation)
 *   arkit       ARKit blendshape weights, for the 3D renderer
 *   doc         description handed to the model — prescriptive about WHEN to fire
 */

export const MUSCLES = [
  // ─────────────────────────── Brow / forehead ───────────────────────────
  {
    id: "frontalis_pars_medialis",
    au: "AU1",
    muscle: "frontalis (pars medialis)",
    region: "brow",
    label: "Inner brow raiser",
    ru: "Поднятие внутренней части брови",
    bilateral: true,
    tau: 190,
    ceiling: 1.0,
    antagonists: ["corrugator_supercilii", "depressor_supercilii"],
    synergists: [],
    arkit: { browInnerUp: 1.0 },
    doc: "Lifts the inner corner of the eyebrow, obliquing it upward. The single most important muscle for sadness, worry, sympathy and pleading. Fire it whenever the person feels concern for someone, distress, or wistfulness. Also fires briefly at the onset of surprise and fear together with AU2. Almost never fires alone in anger.",
  },
  {
    id: "frontalis_pars_lateralis",
    au: "AU2",
    muscle: "frontalis (pars lateralis)",
    region: "brow",
    label: "Outer brow raiser",
    ru: "Поднятие внешней части брови",
    bilateral: true,
    tau: 150,
    ceiling: 1.0,
    antagonists: ["corrugator_supercilii"],
    synergists: [{ id: "levator_palpebrae_superioris", gain: 0.35 }],
    arkit: { browOuterUpLeft: 1.0, browOuterUpRight: 1.0 },
    doc: "Raises the outer eyebrow and arches it. Use for surprise, disbelief, interest and question-asking. A single-sided contraction is the classic sceptical or amused brow-raise — very human, use it for irony and mild doubt. In fear it fires together with AU1 and AU4, which flattens the arch.",
  },
  {
    id: "corrugator_supercilii",
    au: "AU4",
    muscle: "corrugator supercilii",
    region: "brow",
    label: "Brow lowerer / knitter",
    ru: "Сведение бровей",
    bilateral: true,
    tau: 160,
    ceiling: 1.0,
    antagonists: ["frontalis_pars_medialis", "frontalis_pars_lateralis"],
    synergists: [{ id: "depressor_supercilii", gain: 0.6 }],
    arkit: { browDownLeft: 1.0, browDownRight: 1.0 },
    doc: "Draws the eyebrows together and down, creating vertical glabellar lines. The muscle of concentration, difficulty, anger and pain. Fire it at low intensity for any cognitively hard question — this reads as thinking, not as anger. At high intensity with AU5 and AU23 it reads as anger; with AU1 it reads as worry or grief.",
  },
  {
    id: "depressor_supercilii",
    au: "AU4b",
    muscle: "depressor supercilii",
    region: "brow",
    label: "Brow depressor",
    ru: "Опускание брови",
    bilateral: true,
    tau: 170,
    ceiling: 0.9,
    antagonists: ["frontalis_pars_medialis"],
    synergists: [],
    arkit: { browDownLeft: 0.6, browDownRight: 0.6 },
    doc: "Pulls the medial brow straight down without pinching it inward. Combined with corrugator it deepens a frown; alone it makes the eyes look hooded and appraising. Use for scrutiny and suspicion.",
  },
  {
    id: "procerus",
    au: "AU4c",
    muscle: "procerus",
    region: "brow",
    label: "Nasion wrinkler",
    ru: "Морщинка над переносицей",
    bilateral: false,
    tau: 180,
    ceiling: 0.85,
    antagonists: ["frontalis_pars_medialis"],
    synergists: [],
    arkit: { browDownLeft: 0.35, browDownRight: 0.35, noseSneerLeft: 0.2, noseSneerRight: 0.2 },
    doc: "Pulls the skin between the eyebrows downward, producing the horizontal crease at the root of the nose. Signals distaste and irritation. Pair it with AU9 for disgust.",
  },

  // ─────────────────────────────── Eyelids ───────────────────────────────
  {
    id: "levator_palpebrae_superioris",
    au: "AU5",
    muscle: "levator palpebrae superioris",
    region: "eyelid",
    label: "Upper lid raiser",
    ru: "Поднятие верхнего века",
    bilateral: true,
    tau: 90,
    ceiling: 1.0,
    antagonists: ["orbicularis_oculi_pars_palpebralis", "orbicularis_oculi_blink"],
    synergists: [],
    arkit: { eyeWideLeft: 1.0, eyeWideRight: 1.0 },
    doc: "Retracts the upper eyelid so more sclera shows above the iris. Fear, surprise, alarm, and intense anger. This is a fast muscle — raise it in under 120 ms for genuine startle. Sustained high values look unhinged; decay it quickly unless the emotion is fear.",
  },
  {
    id: "orbicularis_oculi_pars_orbitalis",
    au: "AU6",
    muscle: "orbicularis oculi (pars orbitalis)",
    region: "eyelid",
    label: "Cheek raiser (Duchenne marker)",
    ru: "Поднятие щеки — маркер Дюшена",
    bilateral: true,
    tau: 260,
    ceiling: 1.0,
    antagonists: ["levator_palpebrae_superioris"],
    synergists: [],
    arkit: { cheekSquintLeft: 1.0, cheekSquintRight: 1.0, eyeSquintLeft: 0.7, eyeSquintRight: 0.7 },
    doc: "Orbital ring around the eye: narrows the aperture, lifts the cheek, produces crow's feet. This is the honesty signal. A smile without it is read as polite, forced or deceptive; a smile with it is read as felt. If the person genuinely feels warmth, fire this to roughly two-thirds of the zygomaticus value. If they are being polite while unhappy, deliberately leave it near zero.",
  },
  {
    id: "orbicularis_oculi_pars_palpebralis",
    au: "AU7",
    muscle: "orbicularis oculi (pars palpebralis)",
    region: "eyelid",
    label: "Lid tightener",
    ru: "Напряжение век",
    bilateral: true,
    tau: 150,
    ceiling: 1.0,
    antagonists: ["levator_palpebrae_superioris"],
    synergists: [],
    arkit: { eyeSquintLeft: 1.0, eyeSquintRight: 1.0 },
    doc: "Tightens the eyelids and straightens the lower lid margin without lifting the cheek. Reads as focused scrutiny, wariness, or contained anger. Distinct from AU6: this one does not warm the face.",
  },
  {
    id: "levator_palpebrae_inhibition",
    au: "AU43",
    muscle: "levator palpebrae (relaxation)",
    region: "eyelid",
    label: "Lid droop",
    ru: "Опускание век",
    bilateral: true,
    tau: 420,
    ceiling: 1.0,
    antagonists: ["levator_palpebrae_superioris"],
    synergists: [],
    arkit: { eyeBlinkLeft: 0.55, eyeBlinkRight: 0.55 },
    doc: "Slow relaxation of the lid elevator, letting the upper lid settle over the iris. Fatigue, boredom, sadness, sleepiness, or post-emotional deflation. Slow by nature — never step it quickly.",
  },
  {
    id: "orbicularis_oculi_blink",
    au: "AU45",
    muscle: "orbicularis oculi (blink reflex)",
    region: "eyelid",
    label: "Blink",
    ru: "Моргание",
    bilateral: true,
    tau: 45,
    ceiling: 1.0,
    antagonists: ["levator_palpebrae_superioris"],
    synergists: [],
    arkit: { eyeBlinkLeft: 1.0, eyeBlinkRight: 1.0 },
    doc: "A single fast blink. The brainstem already generates spontaneous blinking, so only fire this deliberately for a punctuating blink — after a surprising statement, at a topic change, or as a flinch. Do not use it to fake attention.",
  },

  // ───────────────────────────────── Nose ────────────────────────────────
  {
    id: "levator_labii_alaeque_nasi",
    au: "AU9",
    muscle: "levator labii superioris alaeque nasi",
    region: "nose",
    label: "Nose wrinkler",
    ru: "Наморщивание носа",
    bilateral: true,
    tau: 200,
    ceiling: 1.0,
    antagonists: [],
    synergists: [{ id: "procerus", gain: 0.5 }],
    arkit: { noseSneerLeft: 1.0, noseSneerRight: 1.0, mouthUpperUpLeft: 0.35, mouthUpperUpRight: 0.35 },
    doc: "Wrinkles the nose and lifts the upper lip medially. The core of disgust. A brief low-intensity flash of this during an otherwise pleasant expression is the classic contempt/distaste leak — use it for micro-expressions of suppressed dislike.",
  },
  {
    id: "nasalis_dilator",
    au: "AU38",
    muscle: "nasalis (pars alaris)",
    region: "nose",
    label: "Nostril dilator",
    ru: "Расширение ноздрей",
    bilateral: false,
    tau: 130,
    ceiling: 0.8,
    antagonists: ["nasalis_compressor"],
    synergists: [],
    arkit: {},
    doc: "Flares the nostrils. Driven mostly by breathing, so it is normally handled by the autonomic system. Fire it explicitly for suppressed anger, physical exertion, or a sharp indrawn breath.",
  },
  {
    id: "nasalis_compressor",
    au: "AU39",
    muscle: "nasalis (pars transversa)",
    region: "nose",
    label: "Nostril compressor",
    ru: "Сжатие ноздрей",
    bilateral: false,
    tau: 160,
    ceiling: 0.7,
    antagonists: ["nasalis_dilator"],
    synergists: [],
    arkit: {},
    doc: "Narrows the nostrils, as when smelling something unpleasant or holding one's breath. Rare; pairs with AU9.",
  },

  // ─────────────────────────── Mid-face / mouth ──────────────────────────
  {
    id: "levator_labii_superioris",
    au: "AU10",
    muscle: "levator labii superioris",
    region: "mouth",
    label: "Upper lip raiser",
    ru: "Поднятие верхней губы",
    bilateral: true,
    tau: 190,
    ceiling: 1.0,
    antagonists: ["orbicularis_oris_pressor"],
    synergists: [],
    arkit: { mouthUpperUpLeft: 1.0, mouthUpperUpRight: 1.0 },
    doc: "Raises the upper lip and deepens the nasolabial furrow. Contempt when unilateral, disgust when bilateral with AU9, and part of a snarl with AU4 and AU23.",
  },
  {
    id: "zygomaticus_minor",
    au: "AU11",
    muscle: "zygomaticus minor",
    region: "mouth",
    label: "Nasolabial deepener",
    ru: "Углубление носогубной складки",
    bilateral: true,
    tau: 230,
    ceiling: 0.75,
    antagonists: [],
    synergists: [],
    arkit: { mouthUpperUpLeft: 0.4, mouthUpperUpRight: 0.4 },
    doc: "Subtly deepens the upper nasolabial fold without pulling the corner outward. Adds a trace of sadness or earnestness to a face. Low intensities only.",
  },
  {
    id: "zygomaticus_major",
    au: "AU12",
    muscle: "zygomaticus major",
    region: "mouth",
    label: "Lip corner puller (smile)",
    ru: "Подтягивание уголков губ — улыбка",
    bilateral: true,
    tau: 210,
    ceiling: 1.0,
    antagonists: ["depressor_anguli_oris"],
    synergists: [{ id: "orbicularis_oculi_pars_orbitalis", gain: 0.62 }],
    arkit: { mouthSmileLeft: 1.0, mouthSmileRight: 1.0 },
    doc: "Pulls the lip corners up and back — the smile muscle. Involuntarily recruits AU6 when the feeling is genuine, and the engine will do that for you unless you explicitly hold AU6 down. Intensity is meaning: 0.2 is polite acknowledgement, 0.45 is warm, 0.75 is delighted, above 0.9 is laughter. Slight left/right asymmetry is normal and desirable.",
  },
  {
    id: "buccinator",
    au: "AU14",
    muscle: "buccinator",
    region: "mouth",
    label: "Dimpler",
    ru: "Ямочка на щеке",
    bilateral: true,
    tau: 200,
    ceiling: 0.9,
    antagonists: [],
    synergists: [],
    arkit: { mouthDimpleLeft: 1.0, mouthDimpleRight: 1.0 },
    doc: "Tightens the corner of the mouth inward, creating a dimple-like pucker at the corner. Unilateral AU14 is the canonical contempt/smugness signal. Also appears in scepticism and dry amusement.",
  },
  {
    id: "depressor_anguli_oris",
    au: "AU15",
    muscle: "depressor anguli oris",
    region: "mouth",
    label: "Lip corner depressor",
    ru: "Опускание уголков губ",
    bilateral: true,
    tau: 260,
    ceiling: 1.0,
    antagonists: ["zygomaticus_major"],
    synergists: [],
    arkit: { mouthFrownLeft: 1.0, mouthFrownRight: 1.0 },
    doc: "Pulls the lip corners down. Sadness, disappointment, resignation, disapproval. With AU1 and AU4 it forms the full grief expression. A brief flash of it under a smile is the classic sadness leak.",
  },
  {
    id: "depressor_labii_inferioris",
    au: "AU16",
    muscle: "depressor labii inferioris",
    region: "mouth",
    label: "Lower lip depressor",
    ru: "Опускание нижней губы",
    bilateral: true,
    tau: 190,
    ceiling: 0.9,
    antagonists: ["mentalis"],
    synergists: [],
    arkit: { mouthLowerDownLeft: 1.0, mouthLowerDownRight: 1.0 },
    doc: "Pulls the lower lip down and out, exposing the lower teeth. Disgust, dismay, and part of an open-mouthed shock. Rarely used alone.",
  },
  {
    id: "mentalis",
    au: "AU17",
    muscle: "mentalis",
    region: "mouth",
    label: "Chin raiser",
    ru: "Поднятие подбородка",
    bilateral: false,
    tau: 250,
    ceiling: 1.0,
    antagonists: ["depressor_labii_inferioris"],
    synergists: [],
    arkit: { mouthShrugLower: 1.0 },
    doc: "Pushes the lower lip and chin upward, wrinkling the chin boss. Doubt, stubbornness, holding back tears, suppressing a reply. A very strong signal of restraint — use it whenever the person is choosing not to say something.",
  },
  {
    id: "orbicularis_oris_pucker",
    au: "AU18",
    muscle: "orbicularis oris (constriction)",
    region: "mouth",
    label: "Lip pucker",
    ru: "Вытягивание губ",
    bilateral: false,
    tau: 200,
    ceiling: 1.0,
    antagonists: ["risorius"],
    synergists: [],
    arkit: { mouthPucker: 1.0 },
    doc: 'Draws the lips forward into a small opening. Considering, dubious, about to object. Combined with a head tilt this is the universal "hmm, not sure" face.',
  },
  {
    id: "risorius",
    au: "AU20",
    muscle: "risorius",
    region: "mouth",
    label: "Lip stretcher",
    ru: "Растягивание губ",
    bilateral: true,
    tau: 170,
    ceiling: 1.0,
    antagonists: ["orbicularis_oris_pucker"],
    synergists: [],
    arkit: { mouthStretchLeft: 1.0, mouthStretchRight: 1.0 },
    doc: "Pulls the lip corners straight sideways, flattening the mouth horizontally. Fear, apprehension, wincing, and the awkward grimace of social discomfort. With AU1+AU4+AU5 it completes the fear expression.",
  },
  {
    id: "platysma",
    au: "AU21",
    muscle: "platysma",
    region: "neck",
    label: "Neck tightener",
    ru: "Напряжение платизмы",
    bilateral: true,
    tau: 200,
    ceiling: 0.85,
    antagonists: [],
    synergists: [],
    arkit: {},
    doc: "Tenses the sheet of muscle across the neck, raising visible cords. Strain, effort, revulsion, suppressed emotion. A subtle but powerful realism cue during intense states.",
  },
  {
    id: "orbicularis_oris_funneler",
    au: "AU22",
    muscle: "orbicularis oris (eversion)",
    region: "mouth",
    label: "Lip funneler",
    ru: "Выворачивание губ",
    bilateral: false,
    tau: 190,
    ceiling: 0.85,
    antagonists: ["orbicularis_oris_pressor"],
    synergists: [],
    arkit: { mouthFunnel: 1.0 },
    doc: 'Everts and funnels both lips outward, as when saying "oh" or blowing out. Emphatic speech, exasperation, exhaling.',
  },
  {
    id: "orbicularis_oris_tightener",
    au: "AU23",
    muscle: "orbicularis oris (tightening)",
    region: "mouth",
    label: "Lip tightener",
    ru: "Сжатие губ",
    bilateral: false,
    tau: 180,
    ceiling: 1.0,
    antagonists: ["lips_part"],
    synergists: [],
    arkit: { mouthPressLeft: 0.6, mouthPressRight: 0.6, mouthClose: 0.3 },
    doc: "Narrows and tightens the red of the lips. Anger, determination, containment. With AU4 and AU7 this is the controlled-anger face.",
  },
  {
    id: "orbicularis_oris_pressor",
    au: "AU24",
    muscle: "orbicularis oris (compression)",
    region: "mouth",
    label: "Lip pressor",
    ru: "Сжатие губ вместе",
    bilateral: false,
    tau: 210,
    ceiling: 1.0,
    antagonists: ["lips_part", "orbicularis_oris_funneler"],
    synergists: [{ id: "mentalis", gain: 0.3 }],
    arkit: { mouthPressLeft: 1.0, mouthPressRight: 1.0, mouthClose: 0.5 },
    doc: "Presses the lips together vertically. Withholding, disapproval, resolve, bracing before bad news. Extremely common in real conversation — use it liberally at low intensity as a listening posture.",
  },
  {
    id: "lip_suck",
    au: "AU28",
    muscle: "orbicularis oris (inversion)",
    region: "mouth",
    label: "Lip suck",
    ru: "Втягивание губ",
    bilateral: false,
    tau: 220,
    ceiling: 0.9,
    antagonists: ["orbicularis_oris_funneler"],
    synergists: [],
    arkit: { mouthRollLower: 1.0, mouthRollUpper: 0.7 },
    doc: "Rolls the lips inward over the teeth. Nervousness, holding back, trying not to laugh, embarrassment.",
  },
  {
    id: "lips_part",
    au: "AU25",
    muscle: "depressor labii / relaxation",
    region: "mouth",
    label: "Lips part",
    ru: "Приоткрытие губ",
    bilateral: false,
    tau: 140,
    ceiling: 1.0,
    antagonists: ["orbicularis_oris_pressor", "orbicularis_oris_tightener"],
    synergists: [],
    arkit: { jawOpen: 0.18 },
    doc: "The lips separate slightly without the jaw dropping. Attention, mild surprise, being about to speak, relaxed listening. A face with permanently sealed lips looks dead — keep a little of this alive most of the time.",
  },
  {
    id: "masseter_relaxation",
    au: "AU26",
    muscle: "masseter / temporalis (relaxation)",
    region: "jaw",
    label: "Jaw drop",
    ru: "Опускание челюсти",
    bilateral: false,
    tau: 200,
    ceiling: 1.0,
    antagonists: ["masseter_clench"],
    synergists: [{ id: "lips_part", gain: 0.7 }],
    arkit: { jawOpen: 1.0 },
    doc: "The jaw falls open under its own weight. Surprise, awe, speech. Distinguish from AU27: AU26 is passive and moderate.",
  },
  {
    id: "pterygoid_stretch",
    au: "AU27",
    muscle: "lateral pterygoid",
    region: "jaw",
    label: "Mouth stretch",
    ru: "Широкое открытие рта",
    bilateral: false,
    tau: 170,
    ceiling: 1.0,
    antagonists: ["masseter_clench"],
    synergists: [],
    arkit: { jawOpen: 1.0, mouthStretchLeft: 0.3, mouthStretchRight: 0.3 },
    doc: "Actively pulls the jaw wide open beyond its resting drop. Shock, gasping, shouting, yawning. Strong and brief — hold it and the face looks absurd.",
  },
  {
    id: "masseter_clench",
    au: "AU31",
    muscle: "masseter",
    region: "jaw",
    label: "Jaw clench",
    ru: "Сжатие челюсти",
    bilateral: true,
    tau: 190,
    ceiling: 1.0,
    antagonists: ["masseter_relaxation", "pterygoid_stretch"],
    synergists: [],
    arkit: { mouthPressLeft: 0.3, mouthPressRight: 0.3 },
    doc: "Clenches the jaw, bulging the muscle in front of the ear and sharpening the jawline. Anger, determination, pain endured silently.",
  },
  {
    id: "jaw_thrust",
    au: "AU29",
    muscle: "lateral pterygoid (protrusion)",
    region: "jaw",
    label: "Jaw thrust",
    ru: "Выдвижение челюсти",
    bilateral: false,
    tau: 210,
    ceiling: 0.8,
    antagonists: [],
    synergists: [],
    arkit: { jawForward: 1.0 },
    doc: "Pushes the lower jaw forward. Defiance, challenge, stubbornness. Rare and strong.",
  },
  {
    id: "jaw_lateral",
    au: "AU30",
    muscle: "pterygoid (unilateral)",
    region: "jaw",
    label: "Jaw sideways",
    ru: "Смещение челюсти вбок",
    bilateral: true,
    tau: 230,
    ceiling: 0.7,
    antagonists: [],
    synergists: [],
    arkit: { jawLeft: 1.0, jawRight: 1.0 },
    doc: "Shifts the jaw to one side. A thinking-it-over tic, or irritation. Use sparingly as an idiosyncratic mannerism.",
  },
  {
    id: "buccinator_puff",
    au: "AU33",
    muscle: "buccinator (air retention)",
    region: "mouth",
    label: "Cheek puff",
    ru: "Надувание щёк",
    bilateral: false,
    tau: 240,
    ceiling: 0.9,
    antagonists: ["buccinator_suck"],
    synergists: [],
    arkit: { cheekPuff: 1.0 },
    doc: 'Inflates the cheeks with held air, usually released as a puff. Exasperation, relief, "phew", bracing for effort.',
  },
  {
    id: "buccinator_suck",
    au: "AU35",
    muscle: "buccinator (suction)",
    region: "mouth",
    label: "Cheek suck",
    ru: "Втягивание щёк",
    bilateral: false,
    tau: 250,
    ceiling: 0.75,
    antagonists: ["buccinator_puff"],
    synergists: [],
    arkit: {},
    doc: "Draws the cheeks inward against the teeth. Deliberation, mild disdain, self-restraint.",
  },
  {
    id: "genioglossus_protrusion",
    au: "AU19",
    muscle: "genioglossus",
    region: "mouth",
    label: "Tongue show",
    ru: "Показ языка",
    bilateral: false,
    tau: 200,
    ceiling: 0.6,
    antagonists: [],
    synergists: [{ id: "lips_part", gain: 0.5 }],
    arkit: { tongueOut: 1.0 },
    doc: "The tongue appears between the lips. Concentration on a fiddly task, playfulness, or a brief lip-wetting under stress.",
  },

  // ─────────────────────── Head, gaze, autonomic ─────────────────────────
  {
    id: "head_pitch",
    au: "AU53/54",
    muscle: "splenius / sternocleidomastoid (pitch)",
    region: "head",
    label: "Head pitch (up +, down −)",
    ru: "Наклон головы вверх/вниз",
    bilateral: false,
    tau: 320,
    ceiling: 1.0,
    signed: true,
    antagonists: [],
    synergists: [],
    arkit: {},
    doc: "Positive lifts the chin (confidence, disdain, recall); negative drops it (submission, sadness, concession, close attention). Small values read as natural conversational movement; use ±0.15 constantly rather than holding the head rigid.",
  },
  {
    id: "head_yaw",
    au: "AU51/52",
    muscle: "sternocleidomastoid (rotation)",
    region: "head",
    label: "Head yaw (left +, right −)",
    ru: "Поворот головы влево/вправо",
    bilateral: false,
    tau: 300,
    ceiling: 1.0,
    signed: true,
    antagonists: [],
    synergists: [],
    arkit: {},
    doc: 'Turns the head. A small turn while keeping the eyes on the listener is the classic sceptical or intimate angle. Rapid alternation is a head-shake — a "no".',
  },
  {
    id: "head_roll",
    au: "AU55/56",
    muscle: "trapezius / scalene (tilt)",
    region: "head",
    label: "Head roll / tilt",
    ru: "Боковой наклон головы",
    bilateral: false,
    tau: 340,
    ceiling: 1.0,
    signed: true,
    antagonists: [],
    synergists: [],
    arkit: {},
    doc: "Tilts the head sideways, exposing the neck. Empathy, curiosity, flirtation, and non-threat. One of the strongest warmth cues available and criminally underused — a sympathetic reply almost always carries a tilt.",
  },
  {
    id: "gaze_horizontal",
    au: "AU61/62",
    muscle: "lateral / medial rectus",
    region: "gaze",
    label: "Gaze horizontal (left +, right −)",
    ru: "Взгляд влево/вправо",
    bilateral: false,
    tau: 60,
    ceiling: 1.0,
    signed: true,
    antagonists: [],
    synergists: [],
    arkit: { eyeLookOutLeft: 1.0, eyeLookInRight: 1.0 },
    doc: "Moves both eyes horizontally. Averting sideways signals recall, discomfort or evasion; returning to centre signals engagement. Saccades are ballistic — this muscle is very fast, so step it rather than easing it.",
  },
  {
    id: "gaze_vertical",
    au: "AU63/64",
    muscle: "superior / inferior rectus",
    region: "gaze",
    label: "Gaze vertical (up +, down −)",
    ru: "Взгляд вверх/вниз",
    bilateral: false,
    tau: 60,
    ceiling: 1.0,
    signed: true,
    antagonists: [],
    synergists: [],
    arkit: { eyeLookUpLeft: 1.0, eyeLookUpRight: 1.0, eyeLookDownLeft: 1.0, eyeLookDownRight: 1.0 },
    doc: "Moves both eyes vertically. Up-and-away is visual recall or exasperation; down is shame, sadness, or deference. Looking down while smiling is the shy/pleased combination.",
  },
  {
    id: "pupillary_dilation",
    au: "ANS-1",
    muscle: "dilator / sphincter pupillae",
    region: "autonomic",
    label: "Pupil dilation",
    ru: "Расширение зрачка",
    bilateral: false,
    tau: 700,
    ceiling: 1.0,
    signed: true,
    antagonists: [],
    synergists: [],
    arkit: {},
    doc: "Not under voluntary control — sympathetic arousal widens the pupil, calm narrows it. Set it to match true arousal, including arousal the person is trying to hide. This is the one channel a person cannot fake, so use it to make suppression legible to a careful observer.",
  },
  {
    id: "facial_vasodilation",
    au: "ANS-2",
    muscle: "facial vasculature",
    region: "autonomic",
    label: "Blush / pallor",
    ru: "Румянец / бледность",
    bilateral: false,
    tau: 1600,
    ceiling: 1.0,
    signed: true,
    antagonists: [],
    synergists: [],
    arkit: {},
    doc: "Positive floods the cheeks, ears and throat with colour (embarrassment, attraction, anger, exertion); negative drains it (shock, fear, nausea). Very slow — it builds over a second or two and lingers long after the expression has gone, which is exactly why it reads as involuntary.",
  },
  {
    id: "lacrimal_secretion",
    au: "ANS-3",
    muscle: "lacrimal gland",
    region: "autonomic",
    label: "Tear film / glisten",
    ru: "Слёзная плёнка",
    bilateral: false,
    tau: 2200,
    ceiling: 1.0,
    antagonists: [],
    synergists: [],
    arkit: {},
    doc: "Thickens the tear film so the eyes catch the light. Grief, overwhelming tenderness, pride, or physical pain. Extremely slow to build and slow to clear. Use it rarely; when it appears it dominates the whole face.",
  },
];

export const MUSCLE_BY_ID = Object.fromEntries(MUSCLES.map((m) => [m.id, m]));
export const MUSCLE_IDS = MUSCLES.map((m) => m.id);

export const REGIONS = [
  { id: "brow", label: "Brow / forehead", ru: "Лоб и брови" },
  { id: "eyelid", label: "Eyelids", ru: "Веки" },
  { id: "nose", label: "Nose", ru: "Нос" },
  { id: "mouth", label: "Mouth", ru: "Рот" },
  { id: "jaw", label: "Jaw", ru: "Челюсть" },
  { id: "neck", label: "Neck", ru: "Шея" },
  { id: "head", label: "Head pose", ru: "Поза головы" },
  { id: "gaze", label: "Gaze", ru: "Взгляд" },
  { id: "autonomic", label: "Autonomic", ru: "Вегетативные" },
];

/**
 * Build the Anthropic tool definitions. One tool per muscle, plus a handful of
 * orchestration tools. `strict: true` guarantees the model cannot hand back an
 * input we would have to defensively parse.
 */
export function buildMuscleTools() {
  const tools = MUSCLES.map((m) => {
    const props = {
      intensity: {
        type: "number",
        description: m.signed
          ? `Signed contraction from -1 to 1. 0 is neutral rest. Ceiling ${m.ceiling}.`
          : `Contraction from 0 (relaxed) to 1 (maximum). FACS intensity letters map roughly to A=0.15 B=0.3 C=0.5 D=0.75 E=1.0. Physiological ceiling ${m.ceiling}.`,
      },
      delay_ms: {
        type: "integer",
        description:
          "How long to wait before this muscle starts moving, in ms, measured from the moment the expression is committed. Real expressions are not simultaneous: in a felt emotion the eyes and brow lead the mouth by roughly 40-120 ms, while in a posed or polite expression the mouth goes first. Staggering onsets is one of the strongest cues that an expression is genuine. Use 0 for the leading muscle.",
      },
      onset_ms: {
        type: "integer",
        description: `How long the contraction takes to reach the target, in ms. Typical for this muscle: ${m.tau}. Below 120 reads as a reflex or startle; above 600 reads as a slow deliberate change.`,
      },
      hold_ms: {
        type: "integer",
        description:
          "How long to hold at the target before releasing, in ms. Use 120-300 for a micro-expression, 800-2500 for a normal conversational expression, and 0 to hold indefinitely until the next command.",
      },
      release_ms: {
        type: "integer",
        description:
          "How long the muscle takes to relax back toward baseline after the hold, in ms. Real relaxation is slower than contraction; 1.5x onset is a good default.",
      },
      note: {
        type: "string",
        description: "One short clause on why this muscle is firing right now. Recorded for analysis; not rendered.",
      },
    };
    const required = ["intensity", "delay_ms", "onset_ms", "hold_ms", "release_ms", "note"];

    if (m.bilateral) {
      props.side = {
        type: "string",
        enum: ["left", "right", "both"],
        description:
          'Which side to innervate. Prefer "both" with a small natural asymmetry applied by the engine; use one side deliberately for scepticism, contempt or a wry expression.',
      };
      required.push("side");
    }

    return {
      name: m.id,
      description: `${m.au} — ${m.muscle}. ${m.doc}`,
      strict: true,
      input_schema: {
        type: "object",
        properties: props,
        required,
        additionalProperties: false,
      },
    };
  });

  tools.push({
    name: "commit_expression",
    description:
      "Call this exactly once when every muscle needed for this expression has been innervated. Nothing is sent to the face until you commit. Summarise what the composite pattern should read as to an observer.",
    strict: true,
    input_schema: {
      type: "object",
      properties: {
        reads_as: {
          type: "string",
          description: "What a naive observer would say this face is feeling, in a few words.",
        },
        confidence: {
          type: "number",
          description: "0-1: how confident you are that the pattern is anatomically coherent and will read as intended.",
        },
      },
      required: ["reads_as", "confidence"],
      additionalProperties: false,
    },
  });

  return tools;
}

/** Flat starting state: every muscle at rest. */
export function neutralState() {
  const s = {};
  for (const m of MUSCLES) s[m.id] = { left: 0, right: 0 };
  return s;
}
